=== hongjinqiu/javameta/src/main/java/schema/datasource.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="https://github.com/hongjinqiu/javameta/datasource" 
	xmlns:tns="https://github.com/hongjinqiu/javameta/datasource"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  	jaxb:version="2.1" 
	elementFormDefault="qualified">
	<include schemaLocation="fieldgroup.xsd"></include>
	<annotation>
		<appinfo>
			<jaxb:schemaBindings>
		      <jaxb:package name="com.javameta.model.datasource"/>
		    </jaxb:schemaBindings>
		</appinfo>
		<documentation>
			标题：数据源模型Schema
			版本：v1.0
			创建者：hongjinqiu
			创建时间： 2016-12-12
			最后更新者：hongjinqiu
			最后更新时间： 2016-12-12
		</documentation>
	</annotation>
	
	<!-- 数据源模型 -->
	<element name="datasource">
		<complexType>
			<sequence>
				<element name="id">
					<simpleType>
						<restriction base="string">
							<minLength value="1"></minLength>
						</restriction>
					</simpleType>
				</element>
				<element name="displayName" type="string" default="数据源名称" />
				<element name="inUsedDenyEdit" type="boolean" default="false" />
				<!-- collectionName -->
				<element name="tableName" type="string" default="" />
				<!-- 主数据集 -->
				<element ref="tns:masterData" />
				<!-- 分录数据集 -->
				<element ref="tns:detailData" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<!-- 主数据集 -->
	<element name="masterData">
		<complexType>
			<sequence>
				<element name="id" default="A">
					<simpleType>
						<restriction base="string">
							<pattern value="[A-A]" />
						</restriction>
					</simpleType>
				</element>
				<element name="displayName" type="string" default="主数据集" />
				<element name="allowCopy" type="boolean" default="true" />
				<!-- 固定字段 -->
				<element ref="tns:fixField"></element>
				<!-- 业务字段 -->
				<element ref="tns:bizField"></element>
			</sequence>

		</complexType>
	</element>

	<!-- 分录数据集 -->
	<element name="detailData">
		<complexType>
			<sequence>
				<element name="id" default="B">
					<simpleType>
						<restriction base="string">
							<pattern value="[B-Z]" />
						</restriction>
					</simpleType>
				</element>
				<element name="displayName" type="string" default="分录数据集" />
				<element name="tableName" type="string" default="" />
				<element name="parentFieldId" type="string" default="" />
				<element name="allowEmpty" type="boolean" default="true" minOccurs="0" maxOccurs="1" />
				<!-- <element name="allowEmptyRow" type="boolean" default="false" /> -->
				<element name="allowCopy" type="boolean" default="true" />
				<!-- <element name="readonly" type="boolean" default="false" /> -->
				<!-- 固定字段 -->
				<element ref="tns:fixField"></element>
				<!-- 业务字段 -->
				<element ref="tns:bizField"></element>
			</sequence>

		</complexType>
	</element>
	
	<!-- 固定字段 -->
	<element name="fixField">
		<complexType>
			<sequence>
				<element name="primaryKey" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="id" />
						<attribute name="extends" default="PRIMARY_KEY" />
					</complexType>
				</element>

				<element name="createBy" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="createBy" />
						<attribute name="extends" default="CREATE_BY" />
					</complexType>
				</element>

				<element name="createTime" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="createTime" />
						<attribute name="extends" default="CREATE_TIME" />
					</complexType>
				</element>
				<element name="createUnit" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="createUnit" />
						<attribute name="extends" default="CREATE_UNIT" />
					</complexType>
				</element>
				<element name="modifyBy" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="modifyBy" />
						<attribute name="extends" default="MODIFY_BY" />
					</complexType>
				</element>
				<element name="modifyUnit" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="modifyUnit" />
						<attribute name="extends" default="MODIFY_UNIT" />
					</complexType>
				</element>
				<element name="modifyTime" minOccurs="1" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="modifyTime" />
						<attribute name="extends" default="MODIFY_TIME" />
					</complexType>
				</element>
				<element name="remark" minOccurs="0" maxOccurs="1">
					<complexType>
						<group ref="tns:field-group"></group>
						<attribute name="id" default="remark" />
						<attribute name="extends" default="REMARK" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	
	<!-- 业务字段 -->
	<element name="bizField">
		<complexType>
			<sequence>
				<element ref="tns:field" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<!-- 字段模型 -->
	<element name="field">
		<complexType>
			<group ref="tns:field-group"></group>
			<attribute name="id" />
			<attribute name="extends" />
		</complexType>
	</element>

</schema>

=== hongjinqiu/javameta/src/main/java/demo/cashaccount/ds_cashaccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/main/java/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>CashAccount</id>
	<displayName>现金账户</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_CASHACCOUNT</tableName>
	
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="code">
			</field>
			<field id="" extends="name">
			</field>
			<field id="" extends="mnemonicNo">
			</field>
			<field id="" extends="currencyTypeId">
			</field>
			<field id="" extends="dutyBy">
			</field>
			<field id="" extends="storeAddress">
			</field>
			<field id="" extends="amtSecureBalance">
			</field>
			<field id="" extends="amtOriginalCurrencyBalance">
			</field>
			<field id="" extends="amtLimits">
			</field>
			<field id="" extends="limitsControl">
			</field>
		</bizField>
	</masterData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/sysuser/jm_ds_sysuser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/main/java/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>SysUser</id>
	<displayName>系统用户</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>pub_sysuser</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="code"><!-- subId -->
				<fixReadOnly>true</fixReadOnly>
			</field>
			<field id="" extends="name"><!-- fullName -->
				<fixReadOnly>true</fixReadOnly>
			</field>
			<!-- type,类型,1:系统管理员,2:普通用户 status,子账号当前状态 1正常 -1删除 2冻结,为避免出错,给其添加相应的0-9,忽忽忽忽, fullName:全称,例如:张小姐,映射到name, subId:映射到code, sellerId:卖家ID, sellerNick:卖家昵称,例如:五行色东辉专卖店 nick:昵称,例如:五行色东辉专卖店:小张 -->
			<field id="type" extends="taobaoType">
			</field>
			<field id="status" extends="taobaoStatus"><!-- 没用了 -->
			</field>
			<!-- <field id="" extends="sellerId"> </field> <field id="" extends="sellerNick"> </field> -->
			<field id="" extends="nick">
			</field>
		</bizField>
	</masterData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/bankaccount/ds_bankaccount.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>BankAccount</id>
	<displayName>银行账户</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>pub_bankaccount</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="code">
			</field>
			<field id="" extends="name">
			</field>
			<field id="" extends="mnemonicNo">
			</field>
			<field id="" extends="bankId">
			</field>
			<!-- <field id="" extends="bankAccount"> </field> -->
			<field id="" extends="linkBy">
			</field>
			<field id="" extends="bankAddress">
			</field>
			<field id="" extends="bankPhone">
			</field>
			<field id="" extends="cyberBankUrl">
			</field>
			<field id="" extends="dutyBy">
				<displayName>账户责任人</displayName>
			</field>
			<field id="accountProperty" extends="bankAccountProperty">
			</field>
		</bizField>
	</masterData>
	<detailData>
		<id>B</id>
		<displayName>账户币别</displayName>
		<tableName></tableName>
		<parentFieldId>bankaccount_id</parentFieldId>
		<allowEmpty>true</allowEmpty>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="currencyTypeId">
				<displayName>币别代码</displayName>
				<allowCopy>false</allowCopy>
				<allowDuplicate>false</allowDuplicate>
				<zeroShowEmpty>true</zeroShowEmpty>
			</field>
			<field id="" extends="amtSecureBalance">
			</field>
			<field id="" extends="amtOriginalCurrencyBalance">
			</field>
			<field id="" extends="amtLimits">
			</field>
			<field id="" extends="limitsControl">
			</field>
			<field id="bankaccount_id" extends="PRIMARY_KEY">
			</field>
		</bizField>
	</detailData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/referencelog/jm_ds_referencelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/main/java/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>ReferenceLog</id>
	<displayName>被用资料</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_REFERENCE_LOG</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="ref_datasource_id">
				<displayName>关联方数据源ID</displayName>
			</field>
			<field id="" extends="ref_dataset_id">
				<displayName>关联方主数据集ID</displayName>
			</field>
			<field id="" extends="ref_field_id">
				<displayName>关联方主数据集主键ID</displayName>
			</field>
			<field id="" extends="ref_field_id_value">
				<displayName>关联方主数据集主键ID值</displayName>
			</field>
			<field id="ref_dataset_id_1" extends="ref_dataset_id">
				<displayName>关联方关联字段所在数据集ID</displayName>
			</field>
			<field id="ref_field_id_1" extends="ref_field_id">
				<displayName>关联方关联字段所在数据集主键ID</displayName>
			</field>
			<field id="ref_field_id_value_1" extends="ref_field_id_value">
				<displayName>关联方关联字段所在数据集主键ID值</displayName>
			</field>
			<field id="ref_dataset_id_2" extends="ref_dataset_id">
				<displayName>关联方关联字段所在数据集ID</displayName>
			</field>
			<field id="ref_field_id_2" extends="ref_field_id">
				<displayName>关联方关联字段ID</displayName>
			</field>
			<field id="ref_field_id_value_2" extends="ref_field_id_value">
				<displayName>关联方关联字段ID值</displayName>
			</field>
			
			<field id="" extends="be_ref_datasource_id">
				<displayName>被关联方数据源ID</displayName>
			</field>
			<field id="" extends="be_ref_dataset_id">
				<displayName>被关联方主数据集ID</displayName>
			</field>
			<field id="" extends="be_ref_field_id">
				<displayName>被关联方主数据集主键ID</displayName>
			</field>
			<field id="" extends="be_ref_field_id_value">
				<displayName>被关联方主数据集主键ID值</displayName>
			</field>
			<field id="be_ref_dataset_id_1" extends="be_ref_dataset_id">
				<displayName>被关联方关联字段所主数据集ID</displayName>
			</field>
			<field id="be_ref_field_id_1" extends="be_ref_field_id">
				<displayName>被关联方关联字段所在数据集主键ID</displayName>
			</field>
			<field id="be_ref_field_id_value_1" extends="be_ref_field_id_value">
				<displayName>被关联方关联字段所在主数据集主键ID值</displayName>
			</field>
		</bizField>
	</masterData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/currencytype/ds_currencytype.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>CurrencyType</id>
	<displayName>币别</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_CURRENCYTYPE</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="code">
			</field>
			<field id="" extends="name">
			</field>
			<field id="" extends="currencyTypeSign">
			</field>
			<field id="" extends="roundingWay">
				<fixReadOnly>true</fixReadOnly>
			</field>
			<field id="" extends="amtDecimals">
			</field>
			<field id="" extends="upDecimals">
			</field>
		</bizField>
	</masterData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/gatheringbill/jm_ds_gatheringbill.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/main/java/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>GatheringBill</id>
	<displayName>收款单</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_GATHERINGBILL</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="billDate">
				<defaultValueExpr mode="js">new Date().getFullYear() + "" + (new Date().getMonth() + 1 &lt; 10 ? "0" + (new Date().getMonth() + 1) : (new Date().getMonth() + 1)) + (new Date().getDate() &lt; 10 ? "0" + new Date().getDate() : new Date().getDate())</defaultValueExpr>
			</field>
			<field id="" extends="billNo">
			</field>
			<field id="" extends="property">
			</field>
			<field id="accountId" extends="gatheringAccountId">
			</field>
			<field id="" extends="balanceDate">
				<defaultValueExpr></defaultValueExpr>
			</field>
			<field id="" extends="balanceNo">
			</field>
			<field id="" extends="chamberlainDesc">
			</field>
			<field id="" extends="sysUserId">
				<displayName>采购/业务员</displayName>
				<defaultValueExpr></defaultValueExpr>
			</field>
			<field id="" extends="currencyTypeId">
				<!-- <defaultValueExpr>1</defaultValueExpr> -->
				<fixReadOnly>true</fixReadOnly>
			</field>
			<field id="" extends="exchangeRateShow">
				<fixReadOnly>true</fixReadOnly>
			</field>
			<field id="" extends="exchangeRate">
				<defaultValueExpr>1</defaultValueExpr>
			</field>
			<field id="" extends="amtGathering">
			</field>
			<field id="" extends="amtAgainst">
			</field>
			<field id="" extends="amtNotAgainst">
			</field>
			<field id="" extends="chamberlainName">
			</field>
			<field id="" extends="bankId">
				<displayName>银行代码</displayName>
			</field>
			<field id="" extends="bankAccount">
				<allowEmpty>true</allowEmpty>
			</field>
			<field id="" extends="linkman">
			</field>
			<field id="" extends="linkPhone">
			</field>
		</bizField>
	</masterData>
	<detailData>
		<id>B</id>
		<displayName>收款费用信息</displayName>
		<!-- <allowEmptyRow>false</allowEmptyRow> -->
		<tableName></tableName>
		<parentFieldId>gatheringbill_id</parentFieldId>
		<allowCopy>true</allowCopy>
		<!-- <readonly>false</readonly> -->
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="accountType">
				<displayName>费用账户类型</displayName>
			</field>
			<field id="" extends="accountId">
				<displayName>费用账户</displayName>
			</field>
			<field id="" extends="amtFee">
			</field>
			<field id="gatheringbill_id" extends="PRIMARY_KEY">
			</field>
		</bizField>
	</detailData>
	<detailData>
		<id>C</id>
		<displayName>test</displayName>
		<!-- <allowEmptyRow>false</allowEmptyRow> -->
		<tableName></tableName>
		<parentFieldId>gatheringbill_id</parentFieldId>
		<allowCopy>true</allowCopy>
		<!-- <readonly>false</readonly> -->
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="name" extends="NAME_FIELD">
				<displayName>姓名测试</displayName>
			</field>
			<field id="gatheringbill_id" extends="PRIMARY_KEY">
			</field>
		</bizField>
	</detailData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/referencelog/ds_referencelog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>ReferenceLog</id>
	<displayName>被用资料</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_REFERENCE_LOG</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="ref_datasource_id">
			</field>
			<field id="" extends="ref_dataset_id">
			</field>
			<field id="" extends="ref_field_id">
			</field>
			<field id="" extends="ref_field_id_value">
			</field>
			<field id="" extends="be_ref_datasource_id">
			</field>
			<field id="" extends="be_ref_dataset_id">
			</field>
			<field id="" extends="be_ref_field_id">
			</field>
			<field id="" extends="be_ref_field_id_value">
			</field>
		</bizField>
	</masterData>
</datasource>

=== hongjinqiu/javameta/src/main/java/demo/bank/ds_bank.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/hongjinqiu/javameta/datasource https://raw.githubusercontent.com/hongjinqiu/javameta/master/src/main/java/schema/datasource.xsd">
 -->
<datasource xmlns="https://github.com/hongjinqiu/javameta/datasource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<id>Bank</id>
	<displayName>银行资料</displayName>
	<inUsedDenyEdit>false</inUsedDenyEdit>
	<tableName>PUB_BANK</tableName>
	<masterData>
		<id>A</id>
		<displayName>主数据集</displayName>
		<allowCopy>true</allowCopy>
		<fixField>
			<primaryKey id="id" extends="PRIMARY_KEY" />
			<createBy id="createBy" extends="CREATE_BY" />
			<createTime id="createTime" extends="CREATE_TIME" />
			<createUnit id="createUnit" extends="CREATE_UNIT" />
			<modifyBy id="modifyBy" extends="MODIFY_BY" />
			<modifyUnit id="modifyUnit" extends="MODIFY_UNIT" />
			<modifyTime id="modifyTime" extends="MODIFY_TIME" />
			<remark id="remark" extends="REMARK" />
		</fixField>
		<bizField>
			<field id="" extends="code">
			</field>
			<field id="" extends="name">
			</field>
			<field id="" extends="bankShort">
				<displayName>银行简称</displayName>
			</field>
			<field id="" extends="linkman">
				<displayName>主要联系人</displayName>
			</field>
			<field id="" extends="bankUrl">
			</field>
			<field id="" extends="linkPhone">
			</field>
			<field id="" extends="cusPhone">
			</field>
			<field id="" extends="complainPhone">
			</field>
			<field id="" extends="bankAddress">
				<displayName>银行地址</displayName>
			</field>
		</bizField>
	</masterData>
</datasource>
